openapi: 3.0.0
info:
  title: Spotplay
  description: 'Es una plataforma de musica y mas.....'
  contact:
    email: suport@spotplay.com
  licence:
    name: Apache 2.0
    url: https://apache....
  version: 1.0.0
servers:
- url: http://localhost:4000/api/v1
tags:
- name: Song
  description: Canciones de la aplicacion
- name: User
  description: usuarios de la plataforma
- name: PlayList
  description: Playlist de usuarios
components:
  schemas:
    Song:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        uri: 
          type: string
        duration: 
          type: string
        image: 
          type: string
        idAlbum:
          type: integer
          format: int64
        idArtista: 
          type: integer
          format: int32
        idGender:
          type: integer
          format: int32
    User:
      type: object
      properties:
          id:
            type: integer
            format: int64   
          username: 
            type: string
          password: 
            type: string
paths:
  /user/singup:
    post:
      tags:
      - User
      summary: Crear un usuario
      operationId: createUser
      description: Se creara un usuario para utilizarlo en la aplicacion.
      requestBody:
        description: Ingrese los datos del usuario a crear.
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/xml:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        200:
          description: registro exitoso
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: basd request
          content: {}
        404:
          description: not found
          content: {}
          

        